# Site settings
# {{ site.myvariable }}.

title: Domain Name Search - Periksa ketersediaan domain
author: Farid Nizam
description: >- # this means to ignore newlines until "baseurl:"
  Periksa ketersediaan domain Anda sebelum membeli domain. Cari domain .com, .id dan nama domain top level domain names.
keywords: >- # this means to ignore newlines
  domain, cari domain, domain search, cek domain, domain saya, nama domain, check domain, domain checker, cara mencari domain
baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com

# Favicon
favicon: 'favicon.ico'
# Meta name for Robots
robots: 'index, follow'
# Card Image
cardImageSeo: https://cdn.statically.io/og/Domain%20Name%20Search.jpg

# Umami.is website analytics
umami_websiteId: 5bde902e-c981-44ec-bbd6-e54d9eefeb67
umami_srcUrl: https://slowy.onolune.my.id/umami.js
umami_includeEnvironment: production # development or production
umami_trackerConfig: 'data-auto-track="true" data-do-not-track="true"' # https://umami.is/docs/tracker-config

# Google Site Verification
google_site_verification: _KNDCAEXpqQurf9jCeqoiFWfKcwTvshswIcv818laOc

# Build settings
# theme: minima
plugins:
  - jekyll-sitemap
  - jekyll/minibundle

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
