# Site settings
# {{ site.myvariable }}.

title: Domain Name Search - Periksa ketersediaan domain
short_title: Domain Name Search
author: Farid Nizam
description: >- # this means to ignore newlines until "baseurl:"
  Periksa ketersediaan domain Anda sebelum membeli domain. Cari domain .com, .id dan nama domain top level.
url: 'https://cekdomain.js.org' # the base hostname & protocol for your site, e.g. http://example.com
baseurl: '' # the subpath of your site, e.g. /blog

# CDN
cdn: https://cdn.nomcdn.xyz/cdn?url=cekdomain.js.org

# Favicon, manifest, Meta name for Robots
favicon: 'favicon.ico'
manifest: 'manifest.webmanifest'
robots: 'index, follow'
theme-color: '#b22ccf'
# Metadata
cardImageSeo: https://cdn.statically.io/og/Domain%20Name%20Search.jpg

# Umami.is website analytics
umami_websiteId: 5bde902e-c981-44ec-bbd6-e54d9eefeb67
umami_srcUrl: https://owl.nomsad.com/umami.js
umami_includeEnvironment: production # development or production
umami_trackerConfig: 'data-auto-track="true" data-do-not-track="true"' # https://umami.is/docs/tracker-config

# Google Site Verification
google_site_verification: _KNDCAEXpqQurf9jCeqoiFWfKcwTvshswIcv818laOc

# Build settings
# theme: minima
plugins:
  - jekyll-sitemap
  - jekyll/minibundle

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - README.md
  - netlify.toml
  - .prettierignore
  - .gitignore
